version: 2.1
orbs:
  aws-health: circleci/aws-health@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.3

filters: &filters
  tags:
    only: /.*/

jobs:
  command-tests:
    docker:
      - image: cimg/base:current
    steps:
      - aws-health/check-health
workflows:
  test-deploy:
    jobs:
      - command-tests:
          context: CPE_ORBS_AWS
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: circleci/aws-health
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - command-tests
          context: orb-publisher
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
