version: 2.1
orbs:
  aws-health: circleci/aws-health@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.3

filters: &filters
  tags:
    only: /.*/
executors:
  alpine:
    docker: 
      - image: alpine:latest
  docker-base:
    docker:
      - image: cimg/base:stable
  windows:
    machine:
      image: windows-server-2022-gui:current
    shell: bash.exe
    resource_class: windows.medium
  macos:
    macos:
      xcode: 13.3
workflows:
  test-deploy:
    jobs:
      - aws-health/check-health:
          name: integration-test-<<matrix.executor>>
          context: CPE_ORBS_AWS
          matrix:
            parameters:
              executor: [ "alpine", "docker-base", "windows", "macos" ]
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: circleci/aws-health
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - integration-test-alpine
            - integration-test-docker-base
            - integration-test-windows
            - integration-test-macos
          context: orb-publisher
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
